#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FrameAnimation.Resource", IsApplication=true)]

namespace FrameAnimation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int animate_android = 2130968576;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int A = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int An = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int And = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Andr = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Andre = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Andrea = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Andreas = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int AndreasK = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int AndreasKu = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int AndreasKuu = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int AndreasKuus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int AndreasKuusk = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int AndreasKuuska = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int AndreasKuuskar = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int AndreasKuuskaru = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int animated_android = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
